// Purpose of this is to practice object iteration and infuse it with soccer. 
const trentAlexanderArnold = [
    {
        goals: 0,
        assists: 0,
        keyPasses: 3,
        fantasyAssist: 0,
        shotsOnTarget: 0,
        tacklesWon: 1,
        dispossessed: 2,
        yellowCards: 0,
        redCards: 0,
        accurateCrosses: 4,
        interceptions: 2,
        clearances: 0,
        dribblesSucceeded: 0,
        blockedShots: 1,
        aerialsWon: 1,
        hatTricks: 0,
        penaltiesMissed: 0,
        ownGoals: 0,
        goalsAllowed: 0, 
        cleanSheets: 1
    },
    {
        goals: 0,
        assists: 1,
        keyPasses: 7,
        fantasyAssist: 0,
        shotsOnTarget: 1,
        tacklesWon: 1,
        dispossessed: 1,
        yellowCards: 0,
        redCards: 0,
        accurateCrosses: 5,
        interceptions: 1,
        clearances: 3,
        dribblesSucceeded: 0,
        blockedShots: 0,
        aerialsWon: 2,
        hatTricks: 0,
        penaltiesMissed: 0,
        ownGoals: 0,
        goalsAllowed: 0, 
        cleanSheets: 1
    },
    {
        goals: 0,
        assists: 0,
        keyPasses: 5,
        fantasyAssist: 0,
        shotsOnTarget: 1,
        tacklesWon: 2,
        dispossessed: 1,
        yellowCards: 0,
        redCards: 0,
        accurateCrosses: 3,
        interceptions: 0,
        clearances: 2,
        dribblesSucceeded: 0,
        blockedShots: 0,
        aerialsWon: 0,
        hatTricks: 0,
        penaltiesMissed: 0,
        ownGoals: 0,
        goalsAllowed: 1, 
        cleanSheets: 0
    },
    {
        goals: 0,
        assists: 1,
        keyPasses: 5,
        fantasyAssist: 0,
        shotsOnTarget: 1,
        tacklesWon: 0,
        dispossessed: 0,
        yellowCards: 0,
        redCards: 0,
        accurateCrosses: 3,
        interceptions: 2,
        clearances: 2,
        dribblesSucceeded: 0,
        blockedShots: 0,
        aerialsWon: 2,
        hatTricks: 0,
        penaltiesMissed: 0,
        ownGoals: 0,
        goalsAllowed: 0, 
        cleanSheets: 1
    },
    {
        goals: 0,
        assists: 0,
        keyPasses: 5,
        fantasyAssist: 0,
        shotsOnTarget: 1,
        tacklesWon: 2,
        dispossessed: 1,
        yellowCards: 0,
        redCards: 0,
        accurateCrosses: 3,
        interceptions: 0,
        clearances: 2,
        dribblesSucceeded: 0,
        blockedShots: 0,
        aerialsWon: 0,
        hatTricks: 0,
        penaltiesMissed: 0,
        ownGoals: 0,
        goalsAllowed: 1, 
        cleanSheets: 0
    },
    {
        goals: 0,
        assists: 0,
        keyPasses: 1,
        fantasyAssist: 0,
        shotsOnTarget: 0,
        tacklesWon: 3,
        dispossessed: 0,
        yellowCards: 0,
        redCards: 0,
        accurateCrosses: 2,
        interceptions: 3,
        clearances: 1,
        dribblesSucceeded: 0,
        blockedShots: 1,
        aerialsWon: 1,
        hatTricks: 0,
        penaltiesMissed: 0,
        ownGoals: 0,
        goalsAllowed: 3, 
        cleanSheets: 0
    }
]

for (i = 0; i < trentAlexanderArnold.length; i++) {
    fanstasyPointsDEF = []
    fantasyPointsDEF = (trentAlexanderArnold[i].goals * 10) + (trentAlexanderArnold[i].assists * 8) + (trentAlexanderArnold[i].keyPasses * 2) + (trentAlexanderArnold[i].fantasyAssist * 6) + (trentAlexanderArnold[i].shotsOnTarget * 2) + (trentAlexanderArnold[i].tacklesWon) - (trentAlexanderArnold[i].dispossessed/2) - (trentAlexanderArnold[i].yellowCards * 3) - (trentAlexanderArnold[i].redCards * 6) + (trentAlexanderArnold[i].accurateCrosses) + (trentAlexanderArnold[i].interceptions) + (trentAlexanderArnold[i].clearances * 0.25) + (trentAlexanderArnold[i].dribblesSucceeded) + (trentAlexanderArnold[i].blockedShots/2) + (trentAlexanderArnold[i].aerialsWon) + (trentAlexanderArnold[i].hatTricks * 3) - (trentAlexanderArnold[i].penaltiesMissed * 8) - (trentAlexanderArnold[i].ownGoals * 9) - (trentAlexanderArnold[i].goalsAllowed * 2) + (trentAlexanderArnold[i].cleanSheets * 6)
    console.log(`In Gameweek ${[i + 1]}, Trent Alexander-Arnold scored ${fantasyPointsDEF} fantasy points.`);
}